### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by FerDR89** [ayrton08/e-commerce_backend#1]
Buenas, ¿Cómo estas?.

No me estaba llegando el cod al mail, primero me tiro un 201 y no llego. Luego me tiro un 503 y recién al tercer intento me volvió a tirar un 201 y llegar el código :c

Fijate eso y en cuanto puedas volve a enviarlo por favor.

**Comment by ayrton08** [comment]
Hola @FerDR89 .. ahi subi otro commit con fix, cuando puedas chequear y avisame si sigue pasando lo mismo, gracias genio!
