### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by zapaiamarce** [ayrton08/e-commerce_backend#2]
Te dejo algunas observaciones:

Cuidado con agrupar cosas por categoría (como los schemas) si un schema es propio de un endpoint quizás estaría bueno que esté declarado en la page que corresponde porque es más facil de encontrar y corres menos riesgo de que lo quieras reutilizar para otra cosa y se empiece a embarrar. Hay muchas organizaciones que proponen agrupar componentes de tu sistema por el tipo y no por la jerarquía y por lo general es bardo.

A veces hay un poco de lógica de más en el endpoint. Si tenés una capa de controllers usala para resolver toda la lógica y que el endpoint quede para validar entradas y salidas. 

Ojo con mezclar distintos formatos para los nombres de los archivos. A veces usas camelCase (si lo vas a usar usalo siempre) yo recomiendo usar dash-case.

En lineas generales lo veo bien. Cuidado con los detalles y el orden, en una evaluación técnica a veces va a ser más importante que el código esté impecable antes de que funcione. De todas formas tiene que funcionar. Abrazo!

**Comment by ayrton08** [comment]
Muchas gracias @zapaiamarce por el feedback, me colgue con responder por que estuve trabajando en el M10, ya hice las correcciones que me sugeriste y sigo trabajando en eso.. gracias Sensei! 👍🏼
